NDefines.NGraphics.SUN_HEIGHT = 600
NDefines.NGraphics.SUN_INTENSITY = 0.4
NDefines_Graphics.NGraphics.BLOOM_SCALE = 3.0
NDefines.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.8 --色彩飽和
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_COUNTRY = 0.15 --国土の色の濃さ